## spring, database
spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url : jdbc:mysql://localhost:3306/practiceboard
    username : root
    password : "1234"
    driver-class-name : com.mysql.cj.jdbc.Driver


## Logging
logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    board-practice.board: debug

